a = int (input('ragam aashar :'))
b = int (input('ragam yekan :'))
c = int (input('ragam dahgan :'))
d = int (input('ragam sadgan :'))
e = int (input('ragam hezargan :'))
print((a*0.1)+(b*1)+(c*10)+(d*100)+(e*1000))