a = str(input('enter name a :'))
b = str(input('enter name b :'))
c = str(input('enter name c :'))
d = str(input('enter name d :'))
e = str(input('enter name e :'))
f = str(input('enter name f :'))
g = str(input('enter name g :'))
h = str(input('enter name h :'))
i = str(input('enter name i :'))
j = str(input('enter name j :'))
letter = str(input('enter letter :'))

a = a.capitalize()
b = b.capitalize()
c = c.capitalize()
d = d.capitalize()
e = e.capitalize()
f = f.capitalize()
g = g.capitalize()
h = h.capitalize()
i = i.capitalize()
j = j.capitalize()

aa = a.count(letter)
bb = b.count(letter)
cc = c.count(letter)
dd = d.count(letter)
ee = e.count(letter)
ff = f.count(letter)
gg = g.count(letter)
hh = h.count(letter)
ii = i.count(letter)
jj = j.count(letter)

print(a,'>','count letter :',aa)
print(b,'>','count letter :',bb)
print(c,'>','count letter :',cc)
print(d,'>','count letter :',dd)
print(e,'>','count letter :',ee)
print(f,'>','count letter :',ff)
print(g,'>','count letter :',gg)
print(h,'>','count letter :',hh)
print(i,'>','count letter :',ii)
print(j,'>','count letter :',jj)